### ISSUE TITLE
Document application configuration requirements

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-backend#10]
When deploying the application, the administrator will need to modify config.py, especially the `SQLALCHEMY_DATABASE_URL`.  Some of the options in config.py are probably meant to be ignored by an administrator, and the value `JSON_AS_ASCII` appears twice.

The configuration requirements should be documented in the readme file, with explanation of the relevant configuration options.

These configuration options also need to be used in the python files.  Currently the database username and password is hardcoded in multiple locations:
https://github.com/ulsdevteam/ccvgd-backend/blob/9e08e8795839f11f6519fe18789be0b0e7b5dad1/app_func/advance_search.py#L31-L36
https://github.com/ulsdevteam/ccvgd-backend/blob/9e08e8795839f11f6519fe18789be0b0e7b5dad1/app_func/en_search.py#L28-L34
etc.

Instead, the database credentials should only be represented once, and only in the configuration file.  The configuration file should represent example credentials, which the administrator will be required to customize.

**Comment by JoyDajunSpaceCraft** [comment]
Change the hard code database information to "import config from *", and once you want to change the default database port , name, host, just go to config.py and change mysql_host, etc. 
Thank you so much!

**Comment by ctgraham** [comment]
Tested by redeploying and accessing the /namesearch endpoint.
