### ISSUE TITLE
Consider whether .pyc files should be .gitignored

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-backend#11]
Similar to https://github.com/ulsdevteam/ccvgd-frontend/issues/6, the compiled python bytecode represents more of a distribution or packaged form of the source code, and is probably not appropriate for the git repo.

Consider this default `.gitignore` file for python:
https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by JoyDajunSpaceCraft** [comment]
Add .gitignore file and delete .pyc file. Thank you!

**Comment by ctgraham** [comment]
Confirmed.

**Comment by ctgraham** [comment]
.pyc files are still in `__pycache__` and `app_func/__pycache__` directories in the repo.
