### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-backend#12]
The code in https://github.com/ulsdevteam/ccvgd-backend/tree/d637815432f32695484077d65830252b38dc72dd is a duplicate of https://github.com/ulsdevteam/ccvgd-database/tree/master/pythonScript.

As changes are added to https://github.com/ulsdevteam/ccvgd-database/tree/master/pythonScript, this local copy will become increasingly out of date.  See, for example:
https://github.com/ulsdevteam/ccvgd-database/tree/master/pythonScript

Instead of copying the code from the other repository, please include instructions which link to the other repository, or include the other repository as a git submodule.

**Comment by JoyDajunSpaceCraft** [comment]
I want to keep the **externalFile** dir to reserve external files.
