### ISSUE TITLE
Apply a LICENSE to the repo

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-backend#15]
Code published online should describe in a license what the conditions are for its reuse and modification.

The license may be dictated by any dependencies which you use or package with the application.

If you are not constrained by existing dependencies, [GPL](https://opensource.org/licenses/gpl-license) and [MIT](https://opensource.org/licenses/MIT) licenses are good FLOSS options.

**Comment by JoyDajunSpaceCraft** [comment]
Thank you, I add a LICENSE from MIT into this project.
